# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-06 18:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_remove_item_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='completed',
        ),
    ]
